site_name: D4D tools

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
  custom_dir: overrides

repo_url: https://github.com/openkfw/d4dtools
edit_uri: edit/main/docs/

nav:
  - Introduction: "index.md"
  - "disclaimer.md"
  - Contributing: "contributing.md"
  - "Fact sheets":
    - "mdc.md"
    - "gis.md"
    - "satellites.md"
    - "bim.md"

markdown_extensions:
  - toc
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg