site_name: D4D tools

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - toc.follow
  custom_dir: overrides

repo_url: https://github.com/openkfw/d4dtools
edit_uri: edit/main/docs/

nav:
  - Introduction: "index.md"
  - "disclaimer.md"
  - Contributing: "contributing.md"
  - FAQ: "tech-faq.md"
  - "Fact sheets":
    - "bim.md"
    - "cameras.md"
    - "collaboration.md"
    - "cst.md"
    - "drones.md"
    - "elearning.md"
    - "gis.md"
    - "mms.md"
    - "mdc.md"
    - "rmis.md"
    - "satellites.md"
    - "sensors.md"
    - "climate-adaptation.md"

    
markdown_extensions:
  - toc
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
